### ISSUE TITLE
Errore inaspettato durante la comunicazione con la smart card

### ISSUE THREAD

**Issue by darkbasic** [M0Rf30/cie-middleware-linux#103]
![image](https://github.com/user-attachments/assets/b6a28eb5-1288-4b9d-89b8-382635d55709)

Mi da questo errore mentre provo ad abbinare la CIE. Il repo ufficiale funziona.

Distro: Arch Linux
Lettore: miniLECTOR AIR bit4id

```
[niko@arch-phoenix ~]$ cieid 
java.io.FileNotFoundException: /home/niko/.CIEID/cieid.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at it.ipzs.cieid.util.Utils.getProperty(Utils.java:56)
	at it.ipzs.cieid.MainApplication.initialize(MainApplication.java:53)
	at it.ipzs.cieid.MainApplication.<init>(MainApplication.java:47)
	at it.ipzs.cieid.MainApplication.showUI(MainApplication.java:41)
	at it.ipzs.cieid.MainApplication$1.run(MainApplication.java:31)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
TabbedPan Selected Index: 0
java.io.FileNotFoundException: /home/niko/.CIEID/cieid.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at it.ipzs.cieid.util.Utils.getProperty(Utils.java:56)
	at it.ipzs.cieid.MainFrame.selectHome(MainFrame.java:4596)
	at it.ipzs.cieid.MainFrame.<init>(MainFrame.java:3187)
	at it.ipzs.cieid.IntroFrame$3.actionPerformed(IntroFrame.java:163)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.io.FileNotFoundException: /home/niko/.CIEID/cieid.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at it.ipzs.cieid.util.Utils.getProperty(Utils.java:56)
	at it.ipzs.cieid.MainFrame.selectHome(MainFrame.java:4617)
	at it.ipzs.cieid.MainFrame.<init>(MainFrame.java:3187)
	at it.ipzs.cieid.IntroFrame$3.actionPerformed(IntroFrame.java:163)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
tabbedPanel: javax.swing.JTabbedPane[,200,-65,600x635,invalid,layout=javax.swing.plaf.metal.MetalTabbedPaneUI$TabbedPaneLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=352,maximumSize=,minimumSize=,preferredSize=,haveRegistered=false,tabPlacement=TOP]
TabbedPan Selected Index: 1
File INI:
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
Lib log level: 2
java.io.FileNotFoundException: /home/niko/.CIEID/cieid.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at it.ipzs.cieid.util.Utils.getProperty(Utils.java:56)
	at it.ipzs.cieid.MainFrame.selectHome(MainFrame.java:4596)
	at it.ipzs.cieid.MainFrame$78.run(MainFrame.java:3908)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.io.FileNotFoundException: /home/niko/.CIEID/cieid.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at it.ipzs.cieid.util.Utils.getProperty(Utils.java:56)
	at it.ipzs.cieid.MainFrame.selectHome(MainFrame.java:4617)
	at it.ipzs.cieid.MainFrame$78.run(MainFrame.java:3908)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
TabbedPan Selected Index: 0
Lib log level: 2
```

**Comment by Brunone** [comment]
Buongiorno,
Stesso errore.
Distro: Ubuntu 22.04.4 LTS
Lettore: ACR1581U-C1

**Comment by darkbasic** [comment]
Il commit è il git master di 3 giorni fa, pacchetto da AUR. Il demone era attivo anche perché appena ripassavo al pacchetto binario da upstream funzionava e rilassando al fork smetteva di funzionare.

**Comment by M0Rf30** [comment]
Questo repo non ha avuto nessun commit 3 giorni fa

**Comment by darkbasic** [comment]
Era solo per dire "qualunque fosse il master 3 giorni fa". Il demone l'ho riavviato, altri dettagli non saprei quali darti perché tutto quello che mi ha loggato su shell te l'ho postato. In che modo posso fornirti dei log più verbose?

**Comment by Brunone** [comment]
Spero possa essere utile.
Grazie!

cie-middleware-1.5.2
---
$ ps -e | grep pcsc
   2771 ?        00:00:00 pcscd
---
$ pcsc_scan 
Using reader plug'n play mechanism
Scanning present readers...
0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
1: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader ICC] 01 00
2: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader SAM] 02 00
 
Fri Jul 19 10:09:32 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 5
  Card state: Card inserted, Shared Mode, 
  ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D

ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
+ TS = 3B --> Direct Convention
+ T0 = 8F, Y(1): 1000, K: 15 (historical bytes)
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 01 --> Y(i+1) = 0000, Protocol T = 1 
-----
+ Historical bytes: 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00
  Category indicator byte: 80 (compact TLV data object)
    Tag: 3, len: 1 (card service data byte)
      Card service data byte: 80
        - Application selection: by full DF name
        - EF.DIR and EF.ATR access services: by GET RECORD(s) command
        - Card with MF
    Tag: 6, len: 5 (pre-issuing data)
      Data: 49 54 4A 34 44
    Tag: 1, len: 2 (country code, ISO 3166-1)
      Country code: 0F FF
    Tag: 8, len: 2 (status indicator)
      SW: 9000
+ TCK = 8D (correct checksum)

Possibly identified card (using /home/bruno/.cache/smartcard_list.txt):
3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
	CIE Italian Electronic Identity Card (eID)
 Reader 1: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader ICC] 01 00
  Event number: 0
  Card state: Card removed, 
 Reader 2: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader SAM] 02 00
  Event number: 1
  Card state: Card removed, 
   
Fri Jul 19 10:09:46 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 6
  Card state: Card removed, 
   
Fri Jul 19 10:09:47 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 7
  Card state: Card inserted, 
  ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D

ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
+ TS = 3B --> Direct Convention
+ T0 = 8F, Y(1): 1000, K: 15 (historical bytes)
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 01 --> Y(i+1) = 0000, Protocol T = 1 
-----
+ Historical bytes: 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00
  Category indicator byte: 80 (compact TLV data object)
    Tag: 3, len: 1 (card service data byte)
      Card service data byte: 80
        - Application selection: by full DF name
        - EF.DIR and EF.ATR access services: by GET RECORD(s) command
        - Card with MF
    Tag: 6, len: 5 (pre-issuing data)
      Data: 49 54 4A 34 44
    Tag: 1, len: 2 (country code, ISO 3166-1)
      Country code: 0F FF
    Tag: 8, len: 2 (status indicator)
      SW: 9000
+ TCK = 8D (correct checksum)

Possibly identified card (using /home/bruno/.cache/smartcard_list.txt):
3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
	CIE Italian Electronic Identity Card (eID)
---
$ pcsc_scan 
Using reader plug'n play mechanism
Scanning present readers...
0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
1: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader ICC] 01 00
2: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader SAM] 02 00
 
Fri Jul 19 10:09:32 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 5
  Card state: Card inserted, Shared Mode, 
  ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D

ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
+ TS = 3B --> Direct Convention
+ T0 = 8F, Y(1): 1000, K: 15 (historical bytes)
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 01 --> Y(i+1) = 0000, Protocol T = 1 
-----
+ Historical bytes: 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00
  Category indicator byte: 80 (compact TLV data object)
    Tag: 3, len: 1 (card service data byte)
      Card service data byte: 80
        - Application selection: by full DF name
        - EF.DIR and EF.ATR access services: by GET RECORD(s) command
        - Card with MF
    Tag: 6, len: 5 (pre-issuing data)
      Data: 49 54 4A 34 44
    Tag: 1, len: 2 (country code, ISO 3166-1)
      Country code: 0F FF
    Tag: 8, len: 2 (status indicator)
      SW: 9000
+ TCK = 8D (correct checksum)

Possibly identified card (using /home/bruno/.cache/smartcard_list.txt):
3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
	CIE Italian Electronic Identity Card (eID)
 Reader 1: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader ICC] 01 00
  Event number: 0
  Card state: Card removed, 
 Reader 2: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader SAM] 02 00
  Event number: 1
  Card state: Card removed, 
   
Fri Jul 19 10:09:46 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 6
  Card state: Card removed, 
   
Fri Jul 19 10:09:47 2024
 Reader 0: ACS ACR1581 1S Dual Reader [ACR1581 1S Dual Reader PICC] 00 00
  Event number: 7
  Card state: Card inserted, 
  ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D

ATR: 3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
+ TS = 3B --> Direct Convention
+ T0 = 8F, Y(1): 1000, K: 15 (historical bytes)
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 01 --> Y(i+1) = 0000, Protocol T = 1 
-----
+ Historical bytes: 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00
  Category indicator byte: 80 (compact TLV data object)
    Tag: 3, len: 1 (card service data byte)
      Card service data byte: 80
        - Application selection: by full DF name
        - EF.DIR and EF.ATR access services: by GET RECORD(s) command
        - Card with MF
    Tag: 6, len: 5 (pre-issuing data)
      Data: 49 54 4A 34 44
    Tag: 1, len: 2 (country code, ISO 3166-1)
      Country code: 0F FF
    Tag: 8, len: 2 (status indicator)
      SW: 9000
+ TCK = 8D (correct checksum)

Possibly identified card (using /home/bruno/.cache/smartcard_list.txt):
3B 8F 80 01 80 31 80 65 49 54 4A 34 44 12 0F FF 82 90 00 8D
	CIE Italian Electronic Identity Card (eID)
---

**Comment by M0Rf30** [comment]
Potete confermare che questo commit fixa
https://github.com/M0Rf30/cie-middleware-linux/commit/25e2c3477c5a8d70b406d2fb281634138a8d5863
?

**Comment by Brunone** [comment]
Mi spiace ma non so come fare

**Comment by darkbasic** [comment]
Posso provare il 29, non ho il lettore con me ora

**Comment by M0Rf30** [comment]
aspetteremo il 29 allora

**Comment by Brunone** [comment]
Mi sono fermato qui ("meson setup builddir libs"), sto cercando di risolvere.
Ubuntu 22.04 LTS
$ meson setup builddir libs
The Meson build system
Version: 0.61.2
Source dir: 
/home/bruno/Scaricati/cie-middleware-linux-fix-cie-detection/libs
Build dir: 
/home/bruno/Scaricati/cie-middleware-linux-fix-cie-detection/builddir
Build type: native build
Project name: libcie-pkcs11
Project version: 1.5.2
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 
11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 
11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libcrypto found: YES 3.0.2
Run-time dependency libcrypto++ found: YES 8.6
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency libcryptopp found: NO (tried pkgconfig and cmake)
Run-time dependency cryptopp found: NO (tried pkgconfig and cmake)
Run-time dependency libpcsclite found: YES 1.9.5
Run-time dependency threads found: YES
Run-time dependency libcurl found: YES 7.81.0
Run-time dependency fontconfig found: YES 2.13.1
Run-time dependency freetype2 found: YES 24.1.18
Run-time dependency libpng found: YES 1.6.37
Library libpodofo found: YES
Run-time dependency libxml-2.0 found: YES 2.9.13
Run-time dependency xml2 found: NO (tried pkgconfig and cmake)
Run-time dependency zlib found: YES 1.2.11
Build targets in project: 2
Found ninja-1.10.1 at /usr/bin/ninja
---
# dpkg -l | grep xml2
ii  libxml++2.6-2v5:amd64 
2.40.1-3build3                                amd64        C++ interface 
to the GNOME XML library (libxml2)
ii  libxml-libxml-perl 
2.0207+dfsg+really+2.0134-1                   amd64        Perl 
interface to the libxml2 library
ii  libxml2:amd64 
2.9.13+dfsg-1ubuntu0.4                        amd64        GNOME XML library
ii  libxml2-dev:amd64 
2.9.13+dfsg-1ubuntu0.4                        amd64        GNOME XML 
library - development files
ii  python3-lxml:amd64 
4.8.0-1build1                                 amd64        pythonic 
binding for the libxml2 and libxslt libraries
ii  xml2 
0.5-4build1                                   amd64        Convert 
between XML, HTML, CSV and a line-oriented format
---
# dpkg -l | grep libcrypto
ii  android-libcrypto-utils 
1:10.0.0+r36-9                                amd64        Android 
crypto-utils library
ii  libcrypto++-dev:amd64 
8.6.0-2ubuntu1                                amd64        General 
purpose cryptographic library - C++ development
ii  libcrypto++-utils 
8.6.0-2ubuntu1                                amd64        General 
purpose cryptographic library - utilities and data files
ii  libcrypto++8:amd64 
8.6.0-2ubuntu1                                amd64        General 
purpose cryptographic library - shared library
---

**Comment by M0Rf30** [comment]
> Mi sono fermato qui ("meson setup builddir libs"), sto cercando di risolvere. Ubuntu 22.04 LTS $ meson setup builddir libs The Meson build system Version: 0.61.2 Source dir: /home/bruno/Scaricati/cie-middleware-linux-fix-cie-detection/libs Build dir: /home/bruno/Scaricati/cie-middleware-linux-fix-cie-detection/builddir Build type: native build Project name: libcie-pkcs11 Project version: 1.5.2 C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0") C linker for the host machine: cc ld.bfd 2.38 C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0") C++ linker for the host machine: c++ ld.bfd 2.38 Host machine cpu family: x86_64 Host machine cpu: x86_64 Found pkg-config: /usr/bin/pkg-config (1.8.0) Run-time dependency libcrypto found: YES 3.0.2 Run-time dependency libcrypto++ found: YES 8.6 Found CMake: /usr/bin/cmake (3.22.1) Run-time dependency libcryptopp found: NO (tried pkgconfig and cmake) Run-time dependency cryptopp found: NO (tried pkgconfig and cmake) Run-time dependency libpcsclite found: YES 1.9.5 Run-time dependency threads found: YES Run-time dependency libcurl found: YES 7.81.0 Run-time dependency fontconfig found: YES 2.13.1 Run-time dependency freetype2 found: YES 24.1.18 Run-time dependency libpng found: YES 1.6.37 Library libpodofo found: YES Run-time dependency libxml-2.0 found: YES 2.9.13 Run-time dependency xml2 found: NO (tried pkgconfig and cmake) Run-time dependency zlib found: YES 1.2.11 Build targets in project: 2 Found ninja-1.10.1 at /usr/bin/ninja
> 
> # dpkg -l | grep xml2
> ii libxml++2.6-2v5:amd64 2.40.1-3build3 amd64 C++ interface to the GNOME XML library (libxml2) ii libxml-libxml-perl 2.0207+dfsg+really+2.0134-1 amd64 Perl interface to the libxml2 library ii libxml2:amd64 2.9.13+dfsg-1ubuntu0.4 amd64 GNOME XML library ii libxml2-dev:amd64 2.9.13+dfsg-1ubuntu0.4 amd64 GNOME XML library - development files ii python3-lxml:amd64 4.8.0-1build1 amd64 pythonic binding for the libxml2 and libxslt libraries ii xml2 0.5-4build1 amd64 Convert between XML, HTML, CSV and a line-oriented format
> 
> # dpkg -l | grep libcrypto
> ii android-libcrypto-utils 1:10.0.0+r36-9 amd64 Android crypto-utils library ii libcrypto++-dev:amd64 8.6.0-2ubuntu1 amd64 General purpose cryptographic library - C++ development ii libcrypto++-utils 8.6.0-2ubuntu1 amd64 General purpose cryptographic library - utilities and data files ii libcrypto++8:amd64 8.6.0-2ubuntu1 amd64 General purpose cryptographic library - shared library

devi eseguire l'istruzione successiva del readme
`meson compile -C builddir`
e poi copiare 
`sudo cp builddir/libcie-pkcs11.so /usr/lib`

**Comment by Brunone** [comment]
Carta di Identità Elettronica abbinata correttamente.
Grazie!

**Comment by M0Rf30** [comment]
> Carta di Identità Elettronica abbinata correttamente. Grazie!

Ottimo a sapersi, aspetto anche conferma di @darkbasic e procedo col merge

**Comment by darkbasic** [comment]
@M0Rf30 funziona grazie
