### ISSUE TITLE
Failure on adding graphic signature: incompatibility between jna and ghost4j

### ISSUE THREAD

**Issue by M0Rf30** [M0Rf30/cie-middleware-linux#19]
Allora, ho appena finito di scrivere un bel [pacchetto](https://github.com/rnhmjoj/nixpkgs/commit/bcc2f6a6e47481a322d7bc81fb03cdc202996122) Nix che fa una build riproducibile di cie-middleware-linux usando il branch con podofo originale. 
Ho provato le seguenti cose:
1. abbinare la carta;
2. firmare e verificare la firma (sia CAdES sia PAdES);
3. aggiungere il modulo PKCS#11 al database NSS e fare un login;
4. rimuovere la carta.

Sembra funzionare tutto correttamente tranne la firma PAdES. Se spunto "aggiungi la firma grafica" la firma fallisce con questo errore (che sempre essere un'incompatibilità tra ghost4j e jna):
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Invalid calling convention 63
	at com.sun.jna.Native.createNativeCallback(Native Method)
	at com.sun.jna.CallbackReference.<init>(CallbackReference.java:320)
	at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:506)
	at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:483)
	at com.sun.jna.Function.convertArgument(Function.java:558)
	at com.sun.jna.Function.invoke(Function.java:345)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at jdk.proxy2/jdk.proxy2.$Proxy3.gsapi_set_stdio(Unknown Source)
	at org.ghost4j.Ghostscript.initialize(Ghostscript.java:323)
	at org.ghost4j.renderer.SimpleRenderer.run(SimpleRenderer.java:105)
	at org.ghost4j.renderer.AbstractRemoteRenderer.render(AbstractRemoteRenderer.java:86)
	at org.ghost4j.renderer.AbstractRemoteRenderer.render(AbstractRemoteRenderer.java:70)
	at it.ipzs.cieid.Firma.PdfPreview.<init>(PdfPreview.java:53)
	at it.ipzs.cieid.MainFrame$42.actionPerformed(MainFrame.java:2033)
```
Senza mettera la spunta il programma invece crasha
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbe441740b0, pid=2393655, tid=2393968
#
# JRE version: OpenJDK Runtime Environment (17.0.4+8) (build 17.0.4+8-nixos)
# Java VM: OpenJDK 64-Bit Server VM (17.0.4+8-nixos, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpodofo.so.0.9.8+0x14e0b0]  PoDoFo::PdfPagesTree::GetTotalNumberOfPages() const+0x0
#
```

Un'altra cosa è che ho dovuto [patchare](https://github.com/rnhmjoj/nixpkgs/blob/bcc2f6a6e47481a322d7bc81fb03cdc202996122/pkgs/tools/security/cie-middleware-linux/fix-pcsc-types.patch) un sacco di headers in modo da includere `PCSC/wintypes.h` prima degli altri header di PCSC. Non so per quale motivo ma altrimenti varie typedef che sono usate nell'API non vengono trovati.

Comunque, otimo lavoro, grazie.

_Originally posted by @rnhmjoj in https://github.com/M0Rf30/cie-middleware-linux/issues/8#issuecomment-1236040502_

**Comment by M0Rf30** [comment]
Solved by https://github.com/M0Rf30/cie-middleware-linux/pull/20/commits/db0087d5f1bdc068ed66360e35a6c3c23f7fd7e8

**Comment by rnhmjoj** [comment]
Can confirm it's solved. Thank you.
